version: "3"
services:
  web:
    container_name: testService
    build:
      dockerfile: Dockerfile.dev
      context: .
    depends_on:
      - db
      - redisCache
    ports:
      - "3000:3000"
    volumes:
      - .:/server
    environment:
      - MONGO_HOST=mongodb://db:27017
      - MONGO_DB=test-site
      - REDIS_URL=redis://redisCache:6379
      - APPLICATION_SERVER_PORT=3000
      - APP_FORCE_SHUTDOWN_SECOND=30

  # Database
  db:
    container_name: testServiceMongo
    image: mongo
    ports:
      - "27017:27017"
    restart: always

  # Redis Server
  redisCache:
    container_name: testServiceRedis
    image: redis:alpine
    environment:
      FLASK_ENV: development
    ports:
      - "6379:6379"
    volumes:
      - ./config/redis.conf:/redis.conf
